# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lachlan Dai
tagline:          A Jekyll theme
url:              http://lachlandai.github.io/lanyon
baseurl:          http://lachlandai.github.io/lanyon/
paginate:         5

author:
  name:           Lachlan Dai
  url:            https://twitter.com/lachlandai

# Custom vars
version:          1.1.2

github:
  repo:           https://github.com/lachlandai/lanyon
