# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lachlan Dai
tagline:          'A Jekyll theme'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://lanyon.getpoole.com
baseurl:          '/'
paginate:         5

author:
  name:           'Lachlan Dai'
  url:            https://twitter.com/lachlandai

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/lachlandai
