# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lachlan Dai
tagline:          A Jekyll theme
url:              http://lachlandai.github.io
#baseurl:          http://lachlandai.github.io
paginate:         5

author:
  name:           Lachlan Dai
  url:            https://twitter.com/lachlandai

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/lachlandai/lanyon
